name: Build and Deploy with GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1) Build your site here (Hugo, Jekyll, or custom script).
      #    For example, your Python script that outputs HTML to ./public:
      - name: Build site
        run: |
          pip install markdown
          python generate_index.py

      # 2) Upload your generated site (./public) as a Pages artifact:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
